# Generated by Django 2.2 on 2020-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('kilometers', models.DecimalField(decimal_places=2, max_digits=7)),
                ('miles', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
